### PR TITLE
Adding encryption for JSON requests

### PR DESCRIPTION
**Pull request by 3hoursofsleep**
This uses http headers. I did not add encryption for viewing the html table (/results), since it would only be accessed by clicking on the link in surveyor. HTML links cannot contain headers.

To solve that, I'm working on the researcher sign-in. We'll authenticate based on session.

### CODE REVIEW

**Comment by markwhiting** [comment]
@3hoursofsleep — this is good to go, except for docs, right?

**Comment by sumants-dev** [comment]
I just added some logic that would use /se/{encrypted_string} to get the survey url and worker_id. Should be good to go for our testing with workers next week.

**Review by markwhiting — APPROVED** [review]
Looks good.

At some point we should document this more. But I'm ok to accept for now so we can run tests.

**Comment by markwhiting** [comment]
Yep, I know. I think eventually we would prefer to centralize functionality or surveyor on surveyor and keep individual mapping focused on our internal panel efforts. But I think for now its ok to have it this way if it makes it easier to set up.

**Pull request merged**
