### PR TITLE
Challenge surveys

### PR DESCRIPTION
**Pull request by sumants-dev**
Here, I'm implementing the validation surveys and captcha. I used SVG-Captcha which is opensource. We can use recaptcha from google, but they start tracking stuff and we'll have to register the website with them. We can do that let me know what you wanna do.

https://www.loom.com/share/b2995c2f97864a9fa587d708e7c6908d

### CODE REVIEW

**Review by markwhiting — APPROVED** [review]
This looks great.

As noted on the issue before seeing this, it could be after too, but I'll approve just before now so we can test and decide later on a more detailed design.

**Comment by markwhiting** [comment]
As a side note, what formatter are you using? It looks like its often updating files and I guess it would be good for us to all use the same one so that we don't have lots of formatting changes in commits. 

I don't really mind which one we use. I think I tend to use Prettier with default configurations usually, but if you think theres something better perhaps we can encode that as a standard practice and configuration on the repo?

**Comment by sumants-dev** [comment]
Yeah, I’ll adapt it so their is flag for the beginning or the end.

I have been using the eslint default formatter. Let me see how we can auto format through GitHub.

**Comment by markwhiting** [comment]
Sounds good — I’m fine with formatting before commit, I just think we should all do it the same way :-)

Perhaps just agreeing to all use the same formatter would be an easy start for this. Though a solution that works across repos on GH would also be nice.

**Comment by sumants-dev** [comment]
I can switch to prettier, since it seems that it can be enforced optionally through a json. So we can just commit the json in main directory and then everyone should have same formatting

**Comment by markwhiting** [comment]
Sounds good. Thanks.

**Comment by sumants-dev** [comment]
https://www.loom.com/share/d0b0bacdeb3f473195d5f915b6c550a1
Ok, so this should add new functionalities
1. challenge survey beginning or end
2. math captcha

**Comment by sumants-dev** [comment]
I'll do refactoring and reformatting with prettier on a new branch and issue, so we can make it easier to find on issues if anyone is searching for guidelines and just being safe so things don't break.

Also, I've been sloppy in switching from camel case to snake case. I want to clean that up but on that new branch to be safe.

**Comment by sumants-dev** [comment]
@markwhiting  Can I merge this? I'll do formatting changes in a separate pull request.

**Review by markwhiting — APPROVED** [review]
Looks good, sorry for the delay.

**Pull request merged**
