### PR TITLE
Fixing Multipage Error & Adding Completion Stamps

### PR DESCRIPTION
**Pull request by KaranSampath**
Have modified the code to deal with multipage #40 breaking earlier changes in #42. There still seems to be an error caused by the crypto key which I'm unsure how to rectify @sumants-dev. Have attached the stack trace below:
```powershell
TypeError [ERR_INVALID_ARG_TYPE]: The "password" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at check (internal/crypto/scrypt.js:75:14)
    at Object.scryptSync (internal/crypto/scrypt.js:51:13)
    at Object.<anonymous> (/Users/karansampath/Documents/GitHub/surveyor/built/util.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/karansampath/Documents/GitHub/surveyor/built/routes/survey.js:53:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### CODE REVIEW

**Comment by sumants-dev** [comment]
Ok, I'll look into it now

**Comment by sumants-dev** [comment]
That error is most likely because you don't have the right .env file. Note the iv key here should never be used for production.
```
PORT=4000
MONGO=TRUE
PROD=FALSE
TEST_DB=test_db
TEST_URI=mongodb://localhost:27017
PROD_DB=nothing
PROD_URI=nothing
RANDOM=TESTISRANDOM
TOKEN_KEY=TESTISRANDOM
SECRET_KEY=TESTISRANDOM
ENCRYPT_KEY=TESTISRANDOM
IV_KEY=a0f5c2b327abb291c7cecdea1b2f8cc5 
DOMAIN=http://localhost:4000/
```

**Comment by sumants-dev** [comment]
https://www.loom.com/share/d11c57402cc141a48d1adda53fe6c126
Couple of the conditionals were wonky. Separate out functionalities into separate functions so it is easier to reason.

@KaranSampath  Can you test if the multipage surveys works with more than one question on each page?

**Comment by sumants-dev** [comment]
https://www.loom.com/share/aace88098ef54b7b8f7dc19f0c3f4fdc
It is good to go from my end. I tested the multiple questions.

**Comment by KaranSampath** [comment]
My computer crashed, and I've been unable to run and verify the code since. The following error keeps showing up: 
```
Error: Please set mongo db uri or db
    at Object.<anonymous> (/Users/karansampath/Documents/GitHub/surveyor/built/config.js:18:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/karansampath/Documents/GitHub/surveyor/built/server.js:45:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
The terminal process "zsh '-c', 'npm run start'" terminated with exit code: 1.
```
Looked over it and doesn't seem to have any issues.

**Comment by sumants-dev** [comment]
Your .env file is wrong. The error is coming from config. Remember you have to start mongo with sudo service mongo start.

**Comment by sumants-dev** [comment]
@markwhiting  I've tested this on the server, and I think this should be ready to go. @KaranSampath DM and we can try to resolve these issue on your local machine.

**Review by markwhiting — APPROVED** [review]

**Pull request merged**
